<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Client;

/**
 * GroupStRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{

    public function totalClients(){

        $repository = $this->_em->getRepository(Client::class);

        $query = $repository->createQueryBuilder('c')
            ->select('count(c)')
            ->where('c.active = :status')
            ->setParameter('status', true)
            ->getQuery();

        $resultScalar = $query->getScalarResult();

        return  $resultScalar[0][1];

    }
}
