<?php

namespace AppBundle\Repository;

/**
 * TypeClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
