<?php

namespace AppBundle\Repository;

/**
 * EmployeeTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
