<?php

namespace AppBundle\Repository;

/**
 * EventInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
