<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Expense;
/**
 * ExpenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return mixed
     * INVOICES PAID + INCOMES
     */
    public function expenseWithDates($startDate, $endDate){

        $repository = $this->_em->getRepository(Expense::class);

        $query = $repository->createQueryBuilder('e')
            ->select('sum(e.import)')
            ->andwhere('e.dataCreated >= :startDate')
            ->andwhere('e.dataCreated <= :endDate')
            ->setParameter('startDate', $startDate)
            ->setParameter('endDate', $endDate)
            ->getQuery();

        $resultScalarInvoices = $query->getScalarResult();



        return  $resultScalarInvoices[0][1];
    }
}
