<?php

namespace AppBundle\Repository;
use AppBundle\Entity\GroupSt;

/**
 * GroupStRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupStRepository extends \Doctrine\ORM\EntityRepository
{

    public function totalGroups(){

        $repository = $this->_em->getRepository(GroupSt::class);

        $query = $repository->createQueryBuilder('g')
            ->select('count(g)')
            ->getQuery();

        $resultScalar = $query->getScalarResult();

        return  $resultScalar[0][1];

    }

}
