<?php

namespace AppBundle\Repository;

/**
 * IncomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomeRepository extends \Doctrine\ORM\EntityRepository
{
}
