<?php

namespace AppBundle\Repository;

/**
 * SchedulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedulesRepository extends \Doctrine\ORM\EntityRepository
{
}
