easy_admin:
    entities:
        Expense:
            class: AppBundle\Entity\Expense
            help: ''
            list:
                fields:
                - { property: import }
                - { property: type }
                - { property: dataCreated }
                - { property: dataUpdated }

                actions:
                     - { name: 'edit', icon: 'pencil', label: '' }
                     - { name: 'show', icon: 'search', label: '' }
                     - { name: 'delete', icon: 'trash', label: '' }
            show:
                fields:
                - { property: id }
                - { property: import }
                - { property: type }
                - { property: dataCreated }
                - { property: dataUpdated }
            form:
                fields:
                - { property: import }
                - { property: type }




