imports:
    - { resource: easyadmin/client.yml }
    - { resource: easyadmin/employee.yml }
    - { resource: easyadmin/employee_type.yml }
    - { resource: easyadmin/client_type.yml}
    - { resource: easyadmin/course.yml }
    - { resource: easyadmin/group_st.yml }
    - { resource: easyadmin/classroom.yml }
    - { resource: easyadmin/attendance.yml }
    - { resource: easyadmin/time_table.yml }
    - { resource: easyadmin/menu.yml }
    - { resource: easyadmin/user.yml}
    - { resource: easyadmin/expense.yml }
    - { resource: easyadmin/income.yml }
    - { resource: easyadmin/invoice.yml }



easy_admin:
    assets:

    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    site_name: 'My Cloud <i>Academy</i>'
    design:
        brand_color: '#1ABC9C'
        color_scheme: 'light'
        form_theme: 'vertical'




